# Generated by Django 4.2 on 2023-04-28 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_password"),
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="authors",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_posts",
                to="users.user",
            ),
            preserve_default=False,
        ),
    ]
